### ISSUE TITLE
Support File Upload

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/workflow#10]
### Description

Upload all files to Minio and share the link of the file as part of `formData`. The file upload API will be part of the form-manager service. All files will be uploaded to https://cdn.samagra.io.

`formData` files would be identified as
```json
{
	"selfie": {
		"type": "file",
		"data": "base64 string"
	},
	"name": "nameOfThePerson"
}
```
will be converted to
```json
{
	"selfie": "https://cdn.samagra.io/pathOfTheFile"
	"name": "nameOfThePerson"
}
```

**Comment by amit-s19** [comment]
done
