### ISSUE TITLE
feat: save as draft feature for image upload

### ISSUE THREAD

**Issue by Shruti3004** [Samagra-Development/workflow#24]
### Description

Images are uploaded to the Minio once the user submits the form. But to enable Save as draft feature we should also save the images whenever the file upload event is triggered. In this way we can save the progress of the form.

The following issue can be resolved from here: 
https://github.com/Samagra-Development/workflow/blob/feat/file-upload/packages/enketo-express/public/js/src/module/form-controller.js#L195

### Approach:
- Filtering the events on the basis of the `event == fileUpload`.
- Hitting the `/form/uploadFile` API.
- Testing it with the wrapper codebase.

**Comment by amit-s19** [comment]
Done
