### ISSUE TITLE
Improve Documentation to Easy First Time Setup

### ISSUE THREAD

**Issue by Ansh-Sarkar** [Samagra-Development/workflow#4]
### Description

Improving the Documentation to ease the process of first time setup is essential as the current ```README.md``` documentation **does not outline** the exact steps required for building the project.

Update existing documentation on installation to include exact steps for setup. Contributions to documentations are welcome.

**Comment by Jeevan-Kiran-Lenka** [comment]
Hey @Ansh-Sarkar, I'm new to this project and also very keen to know how it works, I would like to work on this issue kindly assign it to me
