### ISSUE TITLE
Generalised scripts to generate prod secrets

### ISSUE THREAD

**Issue by tushar5526** [Samagra-Development/workflow#44]
Write a CLI script in any language (preferrable python, bash, js) that rotates the secrets in a .env file. 

It should be generalised enough to work with any `.env` file, so we can use it for other projects as well. 

For example: Providing names of variables for which secrets are to be rotated in the `.env` file

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by J0SAL** [comment]
I believe python would be a best choice to work on the issue, can you assign this to me

**Comment by tushar5526** [comment]
Hey @SanjaySinghRajpoot are you planning to pick this up ?

**Comment by SanjaySinghRajpoot** [comment]
[Yes I will make the PR today, ](https://github.com/Samagra-Development/workflow/pull/50)

**Comment by tushar5526** [comment]
Thanks closing this :)
