### ISSUE TITLE
Making Workflow Responsive

### ISSUE THREAD

**Issue by Rohan27s** [Samagra-Development/workflow#61]
### Description

Make the User Interface of workflow responsive for mobile screens

#### Steps followed and expected result

- The UI must be presentable on the mobile screen
- Make it responsive for App.js and GenericForm/index.js

#### Screenshots

![image](https://github.com/Samagra-Development/workflow/assets/74227860/3bc0b89b-1f8b-4b40-9735-f52382b9a999)

![image](https://github.com/Samagra-Development/workflow/assets/74227860/66d769ba-902f-403d-9498-6b0186caa395)

**Comment by amit-s19** [comment]
Closing this with merged PR
