### ISSUE TITLE
Create and Update .env file in apps/wrapper directory through gitpod scripts

### ISSUE THREAD

**Issue by mecskyverse** [Samagra-Development/workflow#68]
### Description

Currently, to see live changes in the app we have to use npm install in ./apps/wrapper directory and then hardcode the .env file in the directory then stop the wrapper container to be able to interact. 
In place of that what we can do is we can automatically add and update a .env file in the wrapper directory through gitpod scripts in our workspace. 
Or we can add a bash script that will install dependencies, stop the wrapper container and start the server all at once with just one script for live interaction.

#### Steps followed and expected result

Add a bash script or update the gitpod script whichever path we want to choose and remove the hardcoded steps to copy-paste .env from here and there.

**Comment by amit-s19** [comment]
Closing this issue with merged PR
